### ISSUE TITLE
Encoding pane problem

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#30]
![paqh9tlklx](https://cloud.githubusercontent.com/assets/862272/7272972/d87fe1a4-e8f7-11e4-8317-25e298ba287a.gif)

It is normal?

**Comment by ColinDuquesnoy** [comment]
Yes this is normal. This panel is dynamic, it become visible only in case of encoding/decoding error. Here you're forcing the display of this panel manually that's why it has some incomplete strings (%s...).

I should remove this panel from the panels menu (and maybe add a dynamic field to easily make the distinction between a static panel and a dynamic one).

**Comment by max107** [comment]
Thanks. Understood.

**Comment by ColinDuquesnoy** [comment]
Dynamic property added, the encodings panel and the search/replace panel won't show up in the panels menu anymore.
