### ISSUE TITLE
Generic code folding with braces

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#34]
![screen shot 2015-04-27 at 13 30 16](https://cloud.githubusercontent.com/assets/862272/7345862/9eba9674-ece1-11e4-9925-ca53f4c413ab.png)

21 line - its ok?

![screen shot 2015-04-27 at 13 30 28](https://cloud.githubusercontent.com/assets/862272/7345865/a18cc836-ece1-11e4-96ca-06cd8c74f028.png)

**Comment by max107** [comment]
Another example

![screen shot 2015-04-27 at 13 41 22](https://cloud.githubusercontent.com/assets/862272/7346038/2c8cf3b0-ece3-11e4-991a-1a8dc8177125.png)

Missing last `},`

**Comment by ColinDuquesnoy** [comment]
Yes that's because the generic fold detector works based on the indentation. You will need to write a custom fold detector that increase fold level when it meets a '{' and decrease fold level when it meets a '}'. This might look a bit like the JSon fold detector: https://github.com/pyQode/pyqode.json/blob/master/pyqode/json/api/folding.py

I planned to write such a fold detector when I'll start working on ``pyqode.javascript`` but I could write it before I start working on javascript (which won't happen before a few months) so that you can already use it for PHP (and other languages such as C, C++, C#).

**Comment by max107** [comment]
> https://github.com/pyQode/pyqode.json/blob/master/pyqode/json/api/folding.py

Thanks. Understood.

**Comment by ColinDuquesnoy** [comment]
I added character based fold detector which should work better for c like languages. The generic editor will automatically used that fold detector for the following languages:

- C++
- C
- C#
- Javascript
- PHP

If I missed a language that user curly braces just let me know, I'll add the missing mimetype.

**Comment by ColinDuquesnoy** [comment]
Tried with this file: https://github.com/ColinDuquesnoy/MellowPlayer/blob/master/src/app/mainwindow.cpp

If I missed a corner case, just comment here I will reopen.
