### ISSUE TITLE
Splittable tabs

### ISSUE THREAD

**Issue by max107** [pyQode/pyQode#39]
Something wrong with splittable widget. Can't set layout `2, 1 1` like in this [video](https://www.youtube.com/watch?v=0oK--lOdYiI)

![sagpgoijq7](https://cloud.githubusercontent.com/assets/862272/7387005/39afc880-ee62-11e4-8a52-4c82c1cbff4f.gif)

**Comment by ColinDuquesnoy** [comment]
Well it's by design. The original tab widget has only one splitter. The first time you split horizontally, the splitter is configured to split horizontally. The second time, when you click "split vertically" on the first tab widget, the splitter get reconfigured to split vertically. It will work if you split vertically the second tab.

Not going to fix this.

**Comment by max107** [comment]
ok
