### ISSUE TITLE
Import Problems on Arch Linux

### ISSUE THREAD

**Issue by jmwright** [pyQode/pyQode#40]
I've got a Arch Linux user who's having troubles that look like they could by Python version related, but we've verified that they aren't.

https://github.com/jmwright/cadquery-freecad-module/issues/53

The error seems to be related to Pygments, and the following import seems to be the first that throws an error.

```python
from pyqode.core.modes import FileWatcherMode
```

I did a clean install of Arch Linux, and cannot reproduce the error. Any thoughts?

**Comment by ColinDuquesnoy** [comment]
> must be string, not None
> 'module' object has no attribute '_vendor'

Looks like the user has a broken sites-packages. I remember I once had a similar problem on Arch, turned out the issue was caused by a broken python package distribution in dist-packages or sites-packages (not sure exactly which package but I remember there was some duplicates packages, I've removed older version manually).

Does "pip2 freeze", "pip2 list" and "pip2 install pip --upgrade" works on the user system??? Might be useful to see the output of those commands...

**Comment by jmwright** [comment]
Those commands worked for him. 

https://github.com/jmwright/cadquery-freecad-module/issues/53#issuecomment-101653620

He's got a new lead on the problem. Still not sure why it's different on his system though. I'm going to go ahead and close this since it doesn't seem PyQode related. 

Thanks for the help.
